# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '*/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: Build 
  inputs:
    command: 'build'
    projects: '*/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Publish Artifact
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.DefaultWorkingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.DefaultWorkingDirectory)' 
    artifactName: 'actualizer'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1 (6bff9de4-6283-43d3-8742-e61e9340b6ca)'
    appType: 'webAppLinux'
    WebAppName: 'actualizer-api'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'